In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
os.chdir("D:\Education\Data Science\Files\Files1")

In [3]:
friends=pd.read_csv('friends.csv')

In [4]:
foes=pd.read_csv('foes.csv')

In [5]:
scores=pd.read_csv('scores.csv')

In [6]:
friends.head()

             person1            person2
0  441e08b1_a0431c52  404021bf_898326ec
1  3f4929ef_956613b7  d6031447_a684b614
2  1f75eb7f_e1d4405b  5ccf7530_5343d32b
3   9b6edd00_179def5  e7d1222f_49ff1c63
4  130181c4_27cb3b23  536c3152_db65659b

In [7]:
friends=friends.rename(columns={'person2':'friend'})

In [8]:
foes.head()

             person1            person2
0  1a78a273_69afff35  cbbb389d_6c185226
1  b49793f1_89131c25  528b6768_4cfc6dfc
2  dae7f2ef_a0eb0f08  f855223d_12422aaf
3   653464a_6d49face  7ac0271c_3677a2d6
4  ae33fd68_8c646d91  b66507c7_44b175d3

In [9]:
foes=foes.rename(columns={'person2':'foe'})

#### Merging Friends and Foes into one dataframe 'relations'

In [10]:
relations=pd.merge(friends,foes,on='person1',how='inner')

In [11]:
relations.head()

             person1             friend                foe
0  3f4929ef_956613b7  d6031447_a684b614  28858cce_80969575
1  3f4929ef_956613b7  d6031447_a684b614  726e8316_87757b02
2  3f4929ef_956613b7  d6031447_a684b614  f46c3323_43363b22
3  3f4929ef_956613b7  d6031447_a684b614  d95f49c1_abefbf21
4  3f4929ef_956613b7  d6031447_a684b614  f03a565d_ae84d384

In [12]:
scores.head()

           person id  score
0  1122b7d5_ed317db7     -2
1  b0177400_be9028c7     -2
2  77ac4e2a_77109d8c     -1
3   49ca4e7d_2eb499f      2
4  9e4a7320_9ebed277     -2

In [13]:
scores=scores.rename(columns={'person id':'person1'})

#### Merging scores with relations dataset

In [14]:
relations=pd.merge(relations,scores,on='person1',how='inner')

In [15]:
relations.head()

             person1             friend                foe  score
0  556ba434_c0ca2371  c38d1b99_3d61be1a  21db496f_e85c2b8a     -2
1  556ba434_c0ca2371  c38d1b99_3d61be1a  6ef90ad9_8bda5830     -2
2  556ba434_c0ca2371  c38d1b99_3d61be1a  9d664ed5_59e02574     -2
3  556ba434_c0ca2371  c38d1b99_3d61be1a  16544885_499ee510     -2
4  556ba434_c0ca2371  c38d1b99_3d61be1a  5520371e_b8c6eb15     -2

In [16]:
unlikely_friend=relations[relations.person1==relations.friend]
unlikely_foe=relations[relations.person1==relations.foe]

In [17]:
unlikely_friend=unlikely_friend.reset_index(drop=True)
unlikely_foe=unlikely_foe.reset_index(drop=True)

In [18]:
unlikely_friend

               person1             friend                foe  score
0     7295669_c50f4599   7295669_c50f4599  1f810a2f_7daa795f     -2
1     7295669_c50f4599   7295669_c50f4599  589e1eb5_94ccd822     -2
2     7295669_c50f4599   7295669_c50f4599  a74d1499_2864adca     -2
3     7295669_c50f4599   7295669_c50f4599  2511a7e7_b685a14c     -2
4     7295669_c50f4599   7295669_c50f4599  e6c591da_7c3aa3df     -2
5     7295669_c50f4599   7295669_c50f4599   c7eb052_36ba27f8     -2
6     7295669_c50f4599   7295669_c50f4599  55663ade_ccff7e48     -2
7     7295669_c50f4599   7295669_c50f4599  b33e692e_210b860c     -2
8     7295669_c50f4599   7295669_c50f4599  1f7fcfae_f1655e45     -2
9     7295669_c50f4599   7295669_c50f4599  f7b184f9_658aa22e     -2
10    7295669_c50f4599   7295669_c50f4599  1acc766e_e18c56af     -2
11    7295669_c50f4599   7295669_c50f4599  83e4b9fb_8db0df01     -2
12    7295669_c50f4599   7295669_c50f4599  eb15b11c_2086cdf0     -2
13    7295669_c50f4599   7295669_c50f4599  84c1aa03_1a20d05c     -2
14    7295669_c50f4599   7295669_c50f4599  ebb75015_52c69b44     -2
15    7295669_c50f4599   7295669_c50f4599  7d48625b_a89a77cc     -2
16    7295669_c50f4599   7295669_c50f4599   19e0b58_52c79607     -2
17    7295669_c50f4599   7295669_c50f4599  af1badfc_c33fb5c7     -2
18    7295669_c50f4599   7295669_c50f4599  969476a7_e28e633d     -2
19    7295669_c50f4599   7295669_c50f4599  c924b499_6d027c33     -2
20    7295669_c50f4599   7295669_c50f4599  3e321287_3ff564d3     -2
21    7295669_c50f4599   7295669_c50f4599  7c4a4902_e49aa078     -2
22    7295669_c50f4599   7295669_c50f4599  cbbb389d_6c185226     -2
23    7295669_c50f4599   7295669_c50f4599  c6bc4578_ae103630     -2
24    7295669_c50f4599   7295669_c50f4599   ac6340b3_be7cf36     -2
25    7295669_c50f4599   7295669_c50f4599  92cbf1ce_29d4c274     -2
26    7295669_c50f4599   7295669_c50f4599  1c5321fd_834765bf     -2
27    7295669_c50f4599   7295669_c50f4599  7b111fe6_d0cc2ab6     -2
28    7295669_c50f4599   7295669_c50f4599  3bc4bcd9_d913e243     -2
29    7295669_c50f4599   7295669_c50f4599  9bb080d0_5473c0c0     -2
..                 ...                ...                ...    ...
339  d835c243_83f3d6ad  d835c243_83f3d6ad  7b0a4631_5cd5a134     -1
340  d835c243_83f3d6ad  d835c243_83f3d6ad  f2928dbd_6b13d297     -1
341  d835c243_83f3d6ad  d835c243_83f3d6ad  afe28fd8_ae1c3f96     -1
342  d835c243_83f3d6ad  d835c243_83f3d6ad  23c7fdb8_e0c331e5     -1
343  d835c243_83f3d6ad  d835c243_83f3d6ad  3829a555_840e4fce     -1
344  d835c243_83f3d6ad  d835c243_83f3d6ad  5eaad312_871a7e48     -1
345  d835c243_83f3d6ad  d835c243_83f3d6ad  67827dbb_c1fc7f05     -1
346  d835c243_83f3d6ad  d835c243_83f3d6ad  ab9db6ea_e42e946c     -1
347  d835c243_83f3d6ad  d835c243_83f3d6ad  67419a66_ee8fe87e     -1
348  d835c243_83f3d6ad  d835c243_83f3d6ad  22e21414_cc06eb7a     -1
349  c8dd2d02_a9ab9b5a  c8dd2d02_a9ab9b5a   ce5f014_8c056377      3
350  c8dd2d02_a9ab9b5a  c8dd2d02_a9ab9b5a   526a12f_a4af99dd      3
351  c8dd2d02_a9ab9b5a  c8dd2d02_a9ab9b5a  857ac4f0_3a785bf0      3
352  c8dd2d02_a9ab9b5a  c8dd2d02_a9ab9b5a  ac6d5b8a_ad430e00      3
353  c8dd2d02_a9ab9b5a  c8dd2d02_a9ab9b5a  9fcff0bc_e61cac07      3
354  c8dd2d02_a9ab9b5a  c8dd2d02_a9ab9b5a  cbbff500_1adc31f6      3
355  c8dd2d02_a9ab9b5a  c8dd2d02_a9ab9b5a  690d3a0c_9545304c      3
356  c8dd2d02_a9ab9b5a  c8dd2d02_a9ab9b5a  be731069_bf767ea3      3
357  c8dd2d02_a9ab9b5a  c8dd2d02_a9ab9b5a  e7ef56e0_2aeb598a      3
358  c8dd2d02_a9ab9b5a  c8dd2d02_a9ab9b5a  62a32695_f1ff0b67      3
359  19f1fc75_a3df0ed1  19f1fc75_a3df0ed1  bc21576f_481556d8      2
360  19f1fc75_a3df0ed1  19f1fc75_a3df0ed1  dea5d9e9_c97b44c0      2
361  19f1fc75_a3df0ed1  19f1fc75_a3df0ed1  75ae4b15_770f3a2f      2
362  19f1fc75_a3df0ed1  19f1fc75_a3df0ed1    a7bcf2_7cd3dc45      2
363  19f1fc75_a3df0ed1  19f1fc75_a3df0ed1   77442d0_ae94d960      2
364  19f1fc75_a3df0ed1  19f1fc75_a3df0ed1  6a067904_a40f1b49      2
365  19f1fc75_a3df0ed1  19f1fc75_a3df0ed1   5fac880_db2439d4      2
366  19f1fc75_a3df0ed1  19f1fc75_a3df0ed1   e1350c8_686c2f5b      2
367  19f1fc75_a3df0ed1  19f1fc75_a3df0ed1  cbf4f13f_58515b52      2
368  19f1fc75_a3df0ed1  19f1fc75_a3df0ed1  cd2807c9_b25e36b3      2

[369 rows x 4 columns]

In [19]:
unlikely_foe.head()

             person1             friend                foe  score
0  428d7973_93c5e9be  95c0ff70_cfa0c123  428d7973_93c5e9be     -1
1  428d7973_93c5e9be  b96c03cc_67baa859  428d7973_93c5e9be     -1
2  428d7973_93c5e9be   611ee08a_ef50b7d  428d7973_93c5e9be     -1
3  428d7973_93c5e9be  3f3e76da_ac5f8ec8  428d7973_93c5e9be     -1
4  428d7973_93c5e9be  3c82c49b_bdcde8f2  428d7973_93c5e9be     -1

In [20]:
len(unlikely_friend.index)

369

In [21]:
len(unlikely_foe.index)

73

In [22]:
unlikely_relation=relations[relations.friend==relations.foe]

In [23]:
len(unlikely_relation.index)

42

In [24]:
unlikely_relation=unlikely_relation.reset_index(drop=True)

In [25]:
list(unlikely_relation.friend.head(9))

['236e4ff5_b0b1c46a',
 'feaab7ff_e1b801ad',
 '66a2770c_34cd2822',
 'c855abb4_a2923e20',
 'e586f515_fa854ee5',
 '8509d089_963b716e',
 '21cf5865_9d9ce6ba',
 'd4099e2_76f0a887',
 '6ef90ad9_8bda5830']

In [26]:
unlikely_foe.person1.unique()

array(['428d7973_93c5e9be'], dtype=object)

In [27]:
unlikely_friend.person1.unique()

array(['7295669_c50f4599', 'b3f834fe_cd3e9607', '8764a06f_b414bfe2',
       '86272b49_1e53876d', '7f2ca170_f4802921', '9a052fea_4dd58d63',
       'd835c243_83f3d6ad', 'c8dd2d02_a9ab9b5a', '19f1fc75_a3df0ed1'],
      dtype=object)

In [28]:
unlikely_relation.friend.unique()

array(['236e4ff5_b0b1c46a', 'feaab7ff_e1b801ad', '66a2770c_34cd2822',
       'c855abb4_a2923e20', 'e586f515_fa854ee5', '8509d089_963b716e',
       '21cf5865_9d9ce6ba', 'd4099e2_76f0a887', '6ef90ad9_8bda5830',
       '48da89f6_55c7495', 'cb0c9599_be6b5297', 'a430d350_380266f3',
       '47c95386_f75c08aa', 'e9a31f1e_2e2f8980', 'afe28fd8_ae1c3f96',
       'c6dcf1ad_a047f1b6', '4ef00044_557c7c45', 'ad0d764f_9c7f8847',
       '5fa54145_ca4f5564', '42054c01_bd9e09f9', '6c4bfad1_9c9043e',
       '74a25e3f_bd77f9d3', '805a3244_aaf74aa2', 'a8a32a9f_ae184492',
       '80c84e2_15b72700', 'ecd9d1f5_406aeaca', 'fa15549f_c9089e92',
       'f9f0b87f_7dc4989d', '2ea9f36d_a5808bf0', '13d1af32_93b2abce',
       '71b351d6_14f10db6', 'cd44da1b_345abf5c', '7a3d8d5f_9c45adbe',
       'ff232b31_ce3e2b9c'], dtype=object)

#### Problem_statement 1:Friendship relations that are most false

In [29]:
person_score=relations.rename(columns={'score':'person_score'})

In [30]:
scores=scores.rename(columns={'person1':'foe','score':'foe_score'})

In [31]:
scores.head()

                 foe  foe_score
0  1122b7d5_ed317db7         -2
1  b0177400_be9028c7         -2
2  77ac4e2a_77109d8c         -1
3   49ca4e7d_2eb499f          2
4  9e4a7320_9ebed277         -2

In [32]:
person_score=pd.merge(person_score,scores,on='foe',how='inner')

In [33]:
person_score.head()

,person1,friend,foe,person_score,foe_score
0,556ba434_c0ca2371,c38d1b99_3d61be1a,21db496f_e85c2b8a,-2,2
1,556ba434_c0ca2371,5f1b2a2c_bd42f449,21db496f_e85c2b8a,-2,2
2,556ba434_c0ca2371,7b313367_90a034e1,21db496f_e85c2b8a,-2,2
3,556ba434_c0ca2371,590acad0_14c8d3ca,21db496f_e85c2b8a,-2,2
4,556ba434_c0ca2371,70bb276f_92564e59,21db496f_e85c2b8a,-2,2

In [34]:
scores=scores.rename(columns={'foe':'friend','foe_score':'friend_score'})

In [35]:
person_score=pd.merge(person_score,scores,on='friend',how='inner')

In [36]:
person_score.head()

,person1,friend,foe,person_score,foe_score,friend_score
0,556ba434_c0ca2371,4ed42ead_334bd0fc,21db496f_e85c2b8a,-2,2,1
1,556ba434_c0ca2371,4ed42ead_334bd0fc,6ef90ad9_8bda5830,-2,-2,1
2,556ba434_c0ca2371,4ed42ead_334bd0fc,16544885_499ee510,-2,-3,1
3,556ba434_c0ca2371,4ed42ead_334bd0fc,c4a4c0e6_c3ac6729,-2,3,1
4,3aef501a_80351c26,4ed42ead_334bd0fc,c4a4c0e6_c3ac6729,-1,3,1

In [37]:
def filter(i):
        if i>0:
            return(1)
        else:
            return(0)

In [38]:
person_score.person_score=person_score.person_score.apply(lambda x:filter(x))
person_score.foe_score=person_score.foe_score.apply(lambda x:filter(x))
person_score.friend_score=person_score.friend_score.apply(lambda x:filter(x))

In [39]:
person_score.head()

,person1,friend,foe,person_score,foe_score,friend_score
0,556ba434_c0ca2371,4ed42ead_334bd0fc,21db496f_e85c2b8a,0,1,1
1,556ba434_c0ca2371,4ed42ead_334bd0fc,6ef90ad9_8bda5830,0,0,1
2,556ba434_c0ca2371,4ed42ead_334bd0fc,16544885_499ee510,0,0,1
3,556ba434_c0ca2371,4ed42ead_334bd0fc,c4a4c0e6_c3ac6729,0,1,1
4,3aef501a_80351c26,4ed42ead_334bd0fc,c4a4c0e6_c3ac6729,0,1,1

In [40]:
amb_foe=person_score[person_score.person_score==person_score.foe_score]

In [41]:
amb_foe=amb_foe.drop(columns=['friend','person_score','foe_score','friend_score'])

In [42]:
amb_friend=person_score[person_score.person_score!=person_score.friend_score]

In [43]:
amb_friend=amb_friend.drop(columns=['foe','person_score','foe_score','friend_score'])

In [44]:
amb_foe=amb_foe.drop_duplicates().reset_index(drop=True)
amb_foe.head()

             person1                foe
0  556ba434_c0ca2371  6ef90ad9_8bda5830
1  556ba434_c0ca2371  16544885_499ee510
2  556ba434_c0ca2371   48da89f6_55c7495
3  556ba434_c0ca2371   d4099e2_76f0a887
4  4ed42ead_334bd0fc  3d54f335_c9d0e769

In [45]:
amb_friend=amb_friend.drop_duplicates().reset_index(drop=True)
amb_friend.head()

             person1             friend
0  556ba434_c0ca2371  4ed42ead_334bd0fc
1  3aef501a_80351c26  4ed42ead_334bd0fc
2  556ba434_c0ca2371  b327c470_4f59511d
3  556ba434_c0ca2371  73904ed7_bdd6c067
4   968af9e_80720411  73904ed7_bdd6c067

In [46]:
len(amb_friend)

1019

In [47]:
amb_friend.person1.unique()

array(['556ba434_c0ca2371', '3aef501a_80351c26', '968af9e_80720411',
       '69d6ab05_946895a4', '6826eae0_1a72ca12', 'bb6c0b99_3b496b3',
       '6113a845_872757cc', '3644b02b_92a552f9', 'ce61b100_6441d8b5',
       '11c8546c_59e94c40', '428d7973_93c5e9be', '182694fc_e85c3338',
       '7d94dd7b_4603a4f3', '52907b87_aa3e7910', 'eb84cdcf_74a3af95',
       '307c710a_b3835244', '7329da4a_a391b41b', '38471523_fe405283',
       '8cce416c_db9f2e72', '58cc74f8_c76ef832', 'f694e6d9_58516ab3',
       'e4f7319d_c82b0c40', '726e8316_87757b02', 'efa814d9_aef152e3',
       '3c7c9b4f_d9ee2550', '4b59af6c_a8db785e', 'b9acc9a_4ae004bd',
       '4af96afc_7f361746', 'd2c95676_56a7db59', 'f0bebaa1_5875b6e4',
       '371dc4e1_9a73d27d', '5cd4deab_eedd7c42', 'bdd7d5b6_1ae73fbe',
       '57aabaee_22fd62bf', '39b10e67_27096fb7', '47c02d3b_4595b8fd',
       'bc7b3ef_5c386e0c', 'ca7cb14e_7cedc83c', '2e2c0f72_7ce29cd5',
       'c5b67732_8d6d7742', '326fced_b2cbc85', '9b6189e3_8826c95',
       '65f99e6f_4324fd83', 'edef6f22_9580b830', '3a827cab_264281a5',
       '26697b96_eb662cf8', 'cb106bbb_15e39af1', 'bea95492_bef086ed',
       'e3e1e401_ca8c2f6f', '62bfcab3_1a1f463', 'd82385be_71ac583a',
       'e9f6d3ce_88d37956', '2043fe18_ed4109a6', '7d4c6fa_581bb82d',
       'e94e5197_ac0cfc01', '673bd66f_89e7b53f', 'b327c470_4f59511d',
       '4ed42ead_334bd0fc', '3779f07c_8ae6ed2e', 'd72298f3_1af033d8',
       '7077ed63_de96f676', '8fa85ae_47e6744b', '46e3a4ab_d4edbfb6',
       '19fb72ee_3184949e', '8fd3a344_70daee4f', 'ba44e6f8_22693293',
       '9779191_d458ccd1', '4b1efc02_d975992f', 'b3d276a7_f7faaee1',
       '256649c4_29402af', '18ecf508_4ebf64bf', '1ebaa216_99c6ddfa',
       '7cb8305f_70a36a5d', '640eaf4c_fa4900a7', 'bb85b041_42e6ab3f',
       '34ddbc2f_91d54040', 'aaf0dc33_5377b4f9', 'a4745ec1_ef71353e',
       'b741320d_282c316c', '248ffccf_7bce26e8', '7e4940e8_aeb1a832',
       '63120810_cd345cbd', '6dacd67_d76e184a', '16e0952b_76037226',
       'f072fc16_5c73fa51', '1202ad96_2c79840f', '81007e87_f944e95b',
       'a769de27_bd24906f', 'af1213cc_2bd1616e', '4d2ec1c8_99b3eedb',
       '5fac6ac7_1a886937', 'bb891fa8_b2f18316', '897097bc_948625b8',
       '1adad7eb_80ee595e', '1587ff39_88bcc57c', '3e2ae3d0_f3d7ff37',
       '4a761c2b_e052c162', 'c7c50da_c9648178', 'fbff46d9_b0741550',
       'a834ac14_9c18db5f', '331610dd_e1bcacaa', 'c0c12699_b50aaefe',
       'f833b27e_60797fcc', '655b5b6_6bd93976', '1e58acc4_98b497a1',
       'b5b7361d_cf586ea0', 'ee1cd543_ab94e0cf', 'c0a95aad_8da750bf',
       'cee65122_90cdc448', '6c9a6b64_2f633d36', '6b33b3f0_80fae05e',
       '4e024b86_5c224973', 'b2021d5b_a560ff3e', '326f263c_4e9e80e4',
       '36f4ed0a_ae3f03e9', '352e8c74_919a8d', 'fab9ad70_55ade1ae',
       '91e51c56_c3397a75', 'b0f094fd_f6562dc3', 'd8b2b13e_79a9ec10',
       '3166f635_244cda27', '864387cb_ebe19acc', 'f1b0c016_a16abf55',
       '94ed1273_fc267678', 'c01b8f2e_62ff56f5', '932297d0_234262e4',
       '6cf84f5d_4c0afa23', 'd91ca5eb_e5c5f173', '97e625e8_2b4cb343',
       '258e3ae3_afaf2804', '758b8c3c_d2b14ae6', 'eb15b11c_2086cdf0',
       'e586f515_fa854ee5', '9f3329db_11165f7e', '365f3577_805b0ba6',
       '6f4f4448_bccd31a8', 'cbb9d8d3_82bb9434', 'bd49ed3f_22e610ca',
       'b4f8cc54_ddd200a5', '2baef089_8be259f9', '645444d5_95e6f031',
       'edd3bd14_3c8c37e6', '6e0038d3_4f8c55cf', '5ad22641_2d2b8aa',
       'ac49a6db_96ef186b', '85675efe_7be8c622', '6c3e1a67_c3516bd3',
       'c8b405ea_192c6ce0', 'c4524078_29268712', 'ac3ba1d6_ced71285',
       '9192a25f_a6483832', 'f9a4b81b_751f4e35', '21499923_e6c9b42b',
       'c42e0b6_4b6add1f', 'a04d96be_4bff4f94', '103e94e7_83ade712',
       '376bae6f_314cbe19', '8f0cbed4_568f2a88', '2bcd6830_b069958',
       '9710bfa0_4b2d7002', 'ebfa355_aa758b4a', '58de09cf_8eab16d9',
       'f1d21a48_5aab6998', '8bfea6e5_fc9819c1', '341022cf_8a9715c4',
       '3df1e53a_dc941f45', 'a7d0895f_2948ad06', '526a12f_a4af99dd',
       'caa12de0_a234df25', 'c8d05a14_5537778', 'ea206bb4_60d4f09b',
       '3e47897c_27551cbf', 'abac7006_dec86d12', 'd42f67e3_8cf01940',
       '7a5bc505_7e202f96', '1a95cb5_8ea2ea1f', '62615ba_f4f42a8e',
       '2217aa2d_225d604e', '9f3874f9_11e0224a', 'edfbcfc7_8f6b302b',
       '6dd57543_f598f862', '5f3d1d37_f32863b2', '12d8c2c7_c18d6dce',
       'd510c4aa_5b290b82', 'b65ec64_7c5dcd9c', '76effdcf_a75d185e',
       '21aedee7_9068bb32', '8260e1c3_f518feae', '2f88e37e_fe93863a',
       'dfdb7cbc_6b071938', '62a32695_f1ff0b67', 'a7eea60d_66a4fb82',
       '1a4472e5_2c85b4e2', '29e3ed08_66de7ee9', '3de6d8a0_74036ad3',
       '77e4333b_485ca1e6', 'b29a809b_4ed1f1d8', '479ee8d3_37fac876',
       '2d28303f_dc2fd3f8', 'ad45ca06_2a4a03d1', 'afae8d3a_24c83574',
       'e7a46602_86841935', '281efba8_9d33b673', 'c32bfa2a_78678200',
       'ca95a094_92996e5d', '4994d25f_fb1355ee', '9a33ce1b_c51f5d7a',
       '70af45c5_3ff6612', '9ef8293_f934e9ef', 'ecb2165e_56c2eefa',
       '1cee6fb9_e19db6af', 'ff73cd11_4dc7bdab', '47ce5315_279cb564',
       '5a921671_15dc8d95', 'fcf42496_cd6004e3', '35f486b4_6220564f',
       'eb2f6f78_9789bb58', 'a043640d_d3e5ce20', 'b551be8_9280b53d',
       'd80e3379_bb910b49', '95564c68_e3e25e4c', '672a69f4_953e947e',
       'b31ff284_25a1eea4', '29f01cc8_1299d7ff', 'd4b27628_a1554e3d',
       'ba83348_f625882d', 'd95ef670_2948deeb', 'e96fc90f_6ba77dcd',
       '7fa6c1d3_4ef6525f', 'e7fe6552_4fc94586', 'fe2d66ca_ebefa510',
       '6b1a5cf7_e29d1e2f', '97e403de_f4e32dd3', 'e5a86e54_6acc1ccf',
       'f9b50ddd_758dfb38', '4fa4df9b_c31a0e1e', '7e6c4790_4a486152',
       '7c28162a_535833', '9965443_d37e20b0', 'd5f9069c_905255c5',
       '2859f13a_7f6124d7', 'fc9f1cf6_5bb90d16', 'bdac1eff_9a4ecb4c',
       '6001155f_409601b6', '43b5b2f8_eda17c15', '1940a646_d4f04a08',
       'd779d2dc_9caae3b5', '9eb41358_42038534', 'cf9aa982_5cfb6080',
       '18603184_9ab390aa', '4d644f88_2f877277', '504c0b4b_aee47c2c',
       'be6e21a8_88dc3d73', '93c780f2_c48944bf', 'c7fa697_bc9cb896',
       '32b22313_127be1ad', '18fd9814_f4024d2a', 'ad0d764f_9c7f8847',
       '822b39fb_60b75a78', '9c83d529_ab519166', '4267d023_55caed82',
       '4d9346d8_4f090633', 'c9e5af71_c58a3fa4', 'd3947341_8a2c68b7',
       'd43d32d9_5851a910', 'e2abac74_786dd8a0', '9778abc2_75264665',
       '2df8175b_fb1de34a', 'c7ce7498_87d2dd8a', 'e5456c59_6dcf165f',
       'ca53b1a6_77f746d6', 'e6195ca4_c9f0bbe1', 'c8dddb62_b96a7c32',
       'e25961f4_139abeb5', 'a13ca06f_a29a51b2', 'e5b1f106_5c6e1222',
       'a562d5f5_714daa7a', '3cea0e0d_5b8acf28', '6f521f11_b1f924f2',
       '83569979_6e3eedcc', '612e3f7a_3ce2519d', '5ba3653c_1c000b94',
       'b3f834fe_cd3e9607', 'c8d96b72_5c65742b', '9b4cd77e_b7304655',
       'afed3574_8fe0ac14', '355fe81b_365814ef', '9bb080d0_5473c0c0',
       '4d315386_f42f5830', 'eee5dfae_262cf07a', 'a95d21fc_36bdff3a',
       'f3b6ac1_9e7e7a65', 'f7620647_971a30a2', '7d3ea0b0_fd3600a1',
       '161b38f3_9c487a6b', '5fd8960c_31d7a887', 'ef3b22e2_3e8bbbc1',
       '9b040e12_a580b407', 'f4732ea6_137cf519', '672ed073_c43e335a',
       '88ed2da5_9979969d', 'b6a6d051_20792743', 'e86c52c_ac87e707',
       'ccc7fb73_c4a2a4d4', '17fd46c1_b7c358f9', '9965da3a_4c8134ba',
       '1801d773_ad28c52f', 'a293b2f9_72b4bf47', 'aa0cc23c_e987f898',
       'a553c9de_882037b8', '5616c572_66e9c1b', 'ad211225_2ee13686',
       '7cdf78f0_1689917e', 'd9d19628_3672bd54', 'ba0f6006_5551ee80',
       '65477840_87aadff8', '1a73ef0d_e071143f', '84dd077d_906ad500',
       'f1b0ad49_506dff3e', '27d53e9d_b6fc3efa', '1754e712_265623ab',
       '486d9cf2_10e9ab4d', '7c57d81d_9e0e3e7a', 'fd6b06fe_5cfa9b5a',
       '53eb9df_4e8e8aab', 'e1eefb96_d6400ac3', '7295669_c50f4599',
       'b320ed34_8247e29', '3a091b53_2b72e7ae', '756cf40c_1ec81372',
       'bd4ddffd_31510789', '96794351_fca63f16', '3fd2053f_68107937',
       '324bc14e_5215b502', '40e49402_2d027a1', '24ca4fa8_f7eb271e',
       'c2f57f16_10ab982c', 'e3c60e46_7459deae', '532743cd_28693c05',
       '530ca7eb_df918243', 'e6b4673c_97005182', '6567e2fb_82003073',
       'c498dd0c_5a7abf77', '127c1bfd_733ab34c', '3edaf519_dc0bbf8d',
       '5ff9c21a_cf537197', '845dda8c_cf903bba', 'ee120865_ac1b6f0f',
       'c9317cf2_82d4d3ff', '93adb15e_a0fd2c52', 'ee231e06_25ef239f',
       '450152ba_5a41fc68', '9eab6682_c53843dc', 'fde25e_d561649c',
       '18268661_26928c7d', 'a499cb2b_60e02fad', 'b4088f7a_3a4a268f',
       '8875cac_3871a3fa', '831b9722_eb0cbd62', '75bbcc68_310a6308',
       '9b9756e9_255c8cce', 'e7b62523_669ecdf7', 'b98e085c_ffd86cc',
       'd64ee5f9_1ecad219', '9a28f729_4484b287', '3945e4e_705859b2',
       '5782501d_d52792d1', '12e75bb6_6a7ef81c', '3e4185fe_48554cfb',
       '2b3ad402_e6ef5696', '8d861cda_5fe3ecb8', '3e7a6ce5_2ca91616',
       '53278979_ac17df93', 'aeefe03c_5a7385cf', 'c7e210d7_13860110',
       '6724b45a_df2b3075', '5a84de_ff37c82d', '530f2b36_f1a0cfd6',
       'fda053a6_8c93abb8', 'bb23e0b6_4caa5f47', '8b6d7232_b60a8f6c',
       '8d8bb078_cacdfee6', '238d4703_545f3d7c', '68119635_86b2a921',
       '560d1488_b69a19f2', '4980ba5b_624efaa3', '7f96e860_32dad934',
       '12318fc_80f41db', '298e21a1_8986d6a', 'b16601b3_eef5b8b7',
       '1e3ce17b_cfc9bf2b', '2dc4bb03_66334770', '32ea397a_235feaef',
       '981b88e5_e248f63a', '62cc9588_ab52061', 'bb2adcba_866587e6',
       '4b5451ee_2ef13224', 'a3432f79_175eb228', 'd8a05627_43f659a5',
       '9357b924_976779ff', 'ce167848_f409eebe', '433bef44_c4a97ab8',
       '694d89f4_49ef4c1c', 'cfe028d3_a5f274d', 'e747d52e_bd28bd4d',
       '46a7b357_8e3e5f0', '4720ff0a_add9f1a4', 'd835c243_83f3d6ad',
       'b82e7c5a_2948d20e', 'aed62174_23764de6', 'ded67a49_550f38f5',
       '847e72d2_8c536fa0', '57a75b35_b123cfb8', '55663ade_ccff7e48',
       '8cc83ee5_1bf8cee6', 'd976d6e3_34d0622a'], dtype=object)

In [48]:
len(amb_foe)

782

In [49]:
amb1=pd.DataFrame(amb_friend.person1)
amb2=pd.DataFrame(amb_foe.person1)

In [50]:
amb=amb1.loc[amb1.person1.isin(amb2.person1)]

In [51]:
scores2=pd.read_csv('scores.csv')

In [52]:
scores2=scores2.rename(columns={'person id':'person1'})

In [53]:
scores3=scores2.loc[scores2.person1.isin(amb.person1)]

In [54]:
len(scores3)

193

In [55]:
len(amb)

586

In [56]:
amb=amb.drop_duplicates().reset_index(drop=True)

In [57]:
len(amb.index)

193

In [58]:
amb

               person1
0    556ba434_c0ca2371
1     968af9e_80720411
2    6826eae0_1a72ca12
3     bb6c0b99_3b496b3
4    6113a845_872757cc
5    428d7973_93c5e9be
6    52907b87_aa3e7910
7    307c710a_b3835244
8    38471523_fe405283
9    f694e6d9_58516ab3
10   e4f7319d_c82b0c40
11   4b59af6c_a8db785e
12   d2c95676_56a7db59
13   f0bebaa1_5875b6e4
14   47c02d3b_4595b8fd
15   ca7cb14e_7cedc83c
16   2e2c0f72_7ce29cd5
17    9b6189e3_8826c95
18   3a827cab_264281a5
19   e94e5197_ac0cfc01
20   b327c470_4f59511d
21   4ed42ead_334bd0fc
22   3779f07c_8ae6ed2e
23   7077ed63_de96f676
24    8fa85ae_47e6744b
25   46e3a4ab_d4edbfb6
26   19fb72ee_3184949e
27   8fd3a344_70daee4f
28   ba44e6f8_22693293
29    9779191_d458ccd1
..                 ...
163  324bc14e_5215b502
164  24ca4fa8_f7eb271e
165  532743cd_28693c05
166  3edaf519_dc0bbf8d
167  5ff9c21a_cf537197
168  93adb15e_a0fd2c52
169  ee231e06_25ef239f
170  a499cb2b_60e02fad
171   8875cac_3871a3fa
172  e7b62523_669ecdf7
173   b98e085c_ffd86cc
174  3e4185fe_48554cfb
175  3e7a6ce5_2ca91616
176  53278979_ac17df93
177    5a84de_ff37c82d
178  fda053a6_8c93abb8
179  bb23e0b6_4caa5f47
180  8b6d7232_b60a8f6c
181  8d8bb078_cacdfee6
182  68119635_86b2a921
183  560d1488_b69a19f2
184    12318fc_80f41db
185   298e21a1_8986d6a
186  32ea397a_235feaef
187  bb2adcba_866587e6
188  d8a05627_43f659a5
189  433bef44_c4a97ab8
190  694d89f4_49ef4c1c
191  e747d52e_bd28bd4d
192  d835c243_83f3d6ad

[193 rows x 1 columns]

In [59]:
Friendships=amb.head(10)

In [60]:
Friendships

             person1
0  556ba434_c0ca2371
1   968af9e_80720411
2  6826eae0_1a72ca12
3   bb6c0b99_3b496b3
4  6113a845_872757cc
5  428d7973_93c5e9be
6  52907b87_aa3e7910
7  307c710a_b3835244
8  38471523_fe405283
9  f694e6d9_58516ab3

In [61]:
Friendships_relationships=amb_friend.head(10)

In [62]:
Friendships_relationships

             person1             friend
0  556ba434_c0ca2371  4ed42ead_334bd0fc
1  3aef501a_80351c26  4ed42ead_334bd0fc
2  556ba434_c0ca2371  b327c470_4f59511d
3  556ba434_c0ca2371  73904ed7_bdd6c067
4   968af9e_80720411  73904ed7_bdd6c067
5  69d6ab05_946895a4  a95d21fc_36bdff3a
6  556ba434_c0ca2371  a5f5f2a1_2f2f4299
7  69d6ab05_946895a4  eee5dfae_262cf07a
8  6826eae0_1a72ca12  428d7973_93c5e9be
9   bb6c0b99_3b496b3  428d7973_93c5e9be

#### Problem 2:Classifing the Good and Bad with having actual ambibuity relationships to the original Scores Dataset

In [63]:
scores2=pd.read_csv('scores.csv')

In [64]:
scores2=scores2.rename(columns={'person id':'person1'})

In [65]:
scores2

                person1  score
0     1122b7d5_ed317db7     -2
1     b0177400_be9028c7     -2
2     77ac4e2a_77109d8c     -1
3      49ca4e7d_2eb499f      2
4     9e4a7320_9ebed277     -2
5     52936684_6bd2c2f3      3
6     bb891fa8_b2f18316      2
7     676be448_ab12f528      2
8     fa71973b_dfeba98c      2
9     3166f635_244cda27      2
10    a043640d_d3e5ce20     -2
11    7fa6c1d3_4ef6525f      3
12    9e858e0f_c50fe1cb      2
13    d1b5f6f0_4731e34e     -2
14    3af85c6e_f4748112      1
15    fc9f1cf6_5bb90d16      1
16    634c20b3_6d1a30df      4
17     a0ba99cd_cbb1d5a     -3
18    d8c7f894_30f97f24     -2
19    6463f790_f24d25a3     -2
20     965a49fe_fa4b2d5      2
21     8390f47d_1ecbe6e     -2
22    33339867_fa9c7bae     -2
23    5ab6fb0e_55091c4d      2
24    354f95a6_f3a3fcda      3
25    3808972d_6dccb11d     -2
26    ef0a6174_164d6764     -2
27    4c427af6_e3aee3b5     -2
28    139a1143_2f017e61     -2
29    2cf3efc3_b2f20d9a      3
...                 ...    ...
1897  44348081_881defa1     -1
1898  49a8ef1b_9478a0da     -1
1899   d64339a_4cfd5078      1
1900  18cd4f6e_822100c7     -2
1901  7a3056e2_f133b6e1      2
1902  3aef501a_80351c26     -1
1903  124119f0_7bd13c7a     -2
1904  bd329c87_ddc0bc01      2
1905  ff4fcf95_ff332153     -2
1906  243a3acc_9ec2034a     -2
1907  1d87cfed_94b71521     -2
1908  3be1998c_341f7318     -2
1909  fe8f223c_5e560689     -1
1910  8506cf40_52804060     -1
1911   ca19cbba_feb5e16      2
1912  8bf42fc8_350a6cf8     -3
1913  b327c470_4f59511d      1
1914   c7e135e_44c23c1d      2
1915  a9c7951f_e609e0a0     -2
1916  fcc490fc_e0776c6b      2
1917   71a6ba12_572b668     -2
1918   86aa844_3610fb9b     -3
1919  47e9c22e_5f94a730     -1
1920  6c12ed31_17e2c385     -2
1921  4fbbac4f_511f5390     -2
1922  8067ca9c_976fdb74     -1
1923  560c450d_3c21c3c5     -2
1924   b98e085c_ffd86cc     -2
1925  73b8016b_82248c8c     -2
1926  371dc4e1_9a73d27d     -2

[1927 rows x 2 columns]

In [66]:
len(scores2)

1927

In [67]:
scores2=scores2.loc[scores2.person1.isin(amb.person1)].reset_index(drop=True)

In [68]:
len(scores2)

193

In [69]:
scores2

               person1  score
0    bb891fa8_b2f18316      2
1    3166f635_244cda27      2
2    fc9f1cf6_5bb90d16      1
3    d2c95676_56a7db59      3
4    77e4333b_485ca1e6     -2
5    52907b87_aa3e7910     -3
6    24ca4fa8_f7eb271e     -1
7    6b33b3f0_80fae05e     -2
8    a562d5f5_714daa7a      2
9    8bfea6e5_fc9819c1     -2
10   2e2c0f72_7ce29cd5      2
11    ba83348_f625882d     -1
12   864387cb_ebe19acc     -2
13   9bb080d0_5473c0c0     -1
14   d80e3379_bb910b49     -2
15   897097bc_948625b8      2
16   d95ef670_2948deeb     -2
17   edfbcfc7_8f6b302b     -2
18   7d3ea0b0_fd3600a1     -1
19   1adad7eb_80ee595e      2
20   3e7a6ce5_2ca91616      2
21   29e3ed08_66de7ee9     -1
22   eee5dfae_262cf07a     -1
23   8d8bb078_cacdfee6     -2
24   21aedee7_9068bb32     -2
25   e4f7319d_c82b0c40      3
26   edd3bd14_3c8c37e6     -3
27    8875cac_3871a3fa      2
28   18ecf508_4ebf64bf      2
29   7e4940e8_aeb1a832      1
..                 ...    ...
163  532743cd_28693c05     -4
164  34ddbc2f_91d54040      2
165  6001155f_409601b6     -2
166   bb6c0b99_3b496b3      1
167  6826eae0_1a72ca12      1
168  428d7973_93c5e9be     -1
169  3e47897c_27551cbf     -1
170   8fa85ae_47e6744b      2
171  c4524078_29268712      2
172  2859f13a_7f6124d7      1
173  694d89f4_49ef4c1c      2
174  19fb72ee_3184949e      2
175  9eb41358_42038534     -2
176  4b1efc02_d975992f      1
177  62a32695_f1ff0b67     -1
178  ea206bb4_60d4f09b      1
179  97e403de_f4e32dd3     -2
180  abac7006_dec86d12     -1
181  640eaf4c_fa4900a7      1
182   655b5b6_6bd93976     -3
183  a553c9de_882037b8     -1
184  e94e5197_ac0cfc01      2
185  d91ca5eb_e5c5f173     -2
186  a293b2f9_72b4bf47     -2
187  6e0038d3_4f8c55cf     -3
188  c0a95aad_8da750bf     -2
189  3df1e53a_dc941f45     -2
190  fda053a6_8c93abb8     -1
191  b327c470_4f59511d      1
192   b98e085c_ffd86cc     -2

[193 rows x 2 columns]

In [70]:
def filter1(i):
    if i<0:
        return(1)
    else:
        return(0)

In [71]:
scores2.score=scores2.score.apply(lambda x:filter1(x))

In [72]:
scores2

               person1  score
0    bb891fa8_b2f18316      0
1    3166f635_244cda27      0
2    fc9f1cf6_5bb90d16      0
3    d2c95676_56a7db59      0
4    77e4333b_485ca1e6      1
5    52907b87_aa3e7910      1
6    24ca4fa8_f7eb271e      1
7    6b33b3f0_80fae05e      1
8    a562d5f5_714daa7a      0
9    8bfea6e5_fc9819c1      1
10   2e2c0f72_7ce29cd5      0
11    ba83348_f625882d      1
12   864387cb_ebe19acc      1
13   9bb080d0_5473c0c0      1
14   d80e3379_bb910b49      1
15   897097bc_948625b8      0
16   d95ef670_2948deeb      1
17   edfbcfc7_8f6b302b      1
18   7d3ea0b0_fd3600a1      1
19   1adad7eb_80ee595e      0
20   3e7a6ce5_2ca91616      0
21   29e3ed08_66de7ee9      1
22   eee5dfae_262cf07a      1
23   8d8bb078_cacdfee6      1
24   21aedee7_9068bb32      1
25   e4f7319d_c82b0c40      0
26   edd3bd14_3c8c37e6      1
27    8875cac_3871a3fa      0
28   18ecf508_4ebf64bf      0
29   7e4940e8_aeb1a832      0
..                 ...    ...
163  532743cd_28693c05      1
164  34ddbc2f_91d54040      0
165  6001155f_409601b6      1
166   bb6c0b99_3b496b3      0
167  6826eae0_1a72ca12      0
168  428d7973_93c5e9be      1
169  3e47897c_27551cbf      1
170   8fa85ae_47e6744b      0
171  c4524078_29268712      0
172  2859f13a_7f6124d7      0
173  694d89f4_49ef4c1c      0
174  19fb72ee_3184949e      0
175  9eb41358_42038534      1
176  4b1efc02_d975992f      0
177  62a32695_f1ff0b67      1
178  ea206bb4_60d4f09b      0
179  97e403de_f4e32dd3      1
180  abac7006_dec86d12      1
181  640eaf4c_fa4900a7      0
182   655b5b6_6bd93976      1
183  a553c9de_882037b8      1
184  e94e5197_ac0cfc01      0
185  d91ca5eb_e5c5f173      1
186  a293b2f9_72b4bf47      1
187  6e0038d3_4f8c55cf      1
188  c0a95aad_8da750bf      1
189  3df1e53a_dc941f45      1
190  fda053a6_8c93abb8      1
191  b327c470_4f59511d      0
192   b98e085c_ffd86cc      1

[193 rows x 2 columns]

In [85]:
scores3=pd.read_csv('scores.csv')

In [86]:
scores3=scores3.rename(columns={'person id':'person1'})

In [87]:
scores3=scores3[~scores3.person1.isin(amb.person1)].reset_index(drop=True)

In [76]:
len(scores3)

1734

In [77]:
scores3

                person1  score
0     1122b7d5_ed317db7     -2
1     b0177400_be9028c7     -2
2     77ac4e2a_77109d8c     -1
3      49ca4e7d_2eb499f      2
4     9e4a7320_9ebed277     -2
5     52936684_6bd2c2f3      3
6     676be448_ab12f528      2
7     fa71973b_dfeba98c      2
8     a043640d_d3e5ce20     -2
9     7fa6c1d3_4ef6525f      3
10    9e858e0f_c50fe1cb      2
11    d1b5f6f0_4731e34e     -2
12    3af85c6e_f4748112      1
13    634c20b3_6d1a30df      4
14     a0ba99cd_cbb1d5a     -3
15    d8c7f894_30f97f24     -2
16    6463f790_f24d25a3     -2
17     965a49fe_fa4b2d5      2
18     8390f47d_1ecbe6e     -2
19    33339867_fa9c7bae     -2
20    5ab6fb0e_55091c4d      2
21    354f95a6_f3a3fcda      3
22    3808972d_6dccb11d     -2
23    ef0a6174_164d6764     -2
24    4c427af6_e3aee3b5     -2
25    139a1143_2f017e61     -2
26    2cf3efc3_b2f20d9a      3
27    40cf7186_6057d385     -2
28    36acd729_414bd216      2
29    df4eaf84_4cb50730     -2
...                 ...    ...
1704  cab5f7a5_232a7e33     -2
1705  29f2d7e9_7f41056f     -3
1706  44348081_881defa1     -1
1707  49a8ef1b_9478a0da     -1
1708   d64339a_4cfd5078      1
1709  18cd4f6e_822100c7     -2
1710  7a3056e2_f133b6e1      2
1711  3aef501a_80351c26     -1
1712  124119f0_7bd13c7a     -2
1713  bd329c87_ddc0bc01      2
1714  ff4fcf95_ff332153     -2
1715  243a3acc_9ec2034a     -2
1716  1d87cfed_94b71521     -2
1717  3be1998c_341f7318     -2
1718  fe8f223c_5e560689     -1
1719  8506cf40_52804060     -1
1720   ca19cbba_feb5e16      2
1721  8bf42fc8_350a6cf8     -3
1722   c7e135e_44c23c1d      2
1723  a9c7951f_e609e0a0     -2
1724  fcc490fc_e0776c6b      2
1725   71a6ba12_572b668     -2
1726   86aa844_3610fb9b     -3
1727  47e9c22e_5f94a730     -1
1728  6c12ed31_17e2c385     -2
1729  4fbbac4f_511f5390     -2
1730  8067ca9c_976fdb74     -1
1731  560c450d_3c21c3c5     -2
1732  73b8016b_82248c8c     -2
1733  371dc4e1_9a73d27d     -2

[1734 rows x 2 columns]

In [78]:
scores3.score=scores3.score.apply(lambda x : filter(x))

In [79]:
scores3

                person1  score
0     1122b7d5_ed317db7      0
1     b0177400_be9028c7      0
2     77ac4e2a_77109d8c      0
3      49ca4e7d_2eb499f      1
4     9e4a7320_9ebed277      0
5     52936684_6bd2c2f3      1
6     676be448_ab12f528      1
7     fa71973b_dfeba98c      1
8     a043640d_d3e5ce20      0
9     7fa6c1d3_4ef6525f      1
10    9e858e0f_c50fe1cb      1
11    d1b5f6f0_4731e34e      0
12    3af85c6e_f4748112      1
13    634c20b3_6d1a30df      1
14     a0ba99cd_cbb1d5a      0
15    d8c7f894_30f97f24      0
16    6463f790_f24d25a3      0
17     965a49fe_fa4b2d5      1
18     8390f47d_1ecbe6e      0
19    33339867_fa9c7bae      0
20    5ab6fb0e_55091c4d      1
21    354f95a6_f3a3fcda      1
22    3808972d_6dccb11d      0
23    ef0a6174_164d6764      0
24    4c427af6_e3aee3b5      0
25    139a1143_2f017e61      0
26    2cf3efc3_b2f20d9a      1
27    40cf7186_6057d385      0
28    36acd729_414bd216      1
29    df4eaf84_4cb50730      0
...                 ...    ...
1704  cab5f7a5_232a7e33      0
1705  29f2d7e9_7f41056f      0
1706  44348081_881defa1      0
1707  49a8ef1b_9478a0da      0
1708   d64339a_4cfd5078      1
1709  18cd4f6e_822100c7      0
1710  7a3056e2_f133b6e1      1
1711  3aef501a_80351c26      0
1712  124119f0_7bd13c7a      0
1713  bd329c87_ddc0bc01      1
1714  ff4fcf95_ff332153      0
1715  243a3acc_9ec2034a      0
1716  1d87cfed_94b71521      0
1717  3be1998c_341f7318      0
1718  fe8f223c_5e560689      0
1719  8506cf40_52804060      0
1720   ca19cbba_feb5e16      1
1721  8bf42fc8_350a6cf8      0
1722   c7e135e_44c23c1d      1
1723  a9c7951f_e609e0a0      0
1724  fcc490fc_e0776c6b      1
1725   71a6ba12_572b668      0
1726   86aa844_3610fb9b      0
1727  47e9c22e_5f94a730      0
1728  6c12ed31_17e2c385      0
1729  4fbbac4f_511f5390      0
1730  8067ca9c_976fdb74      0
1731  560c450d_3c21c3c5      0
1732  73b8016b_82248c8c      0
1733  371dc4e1_9a73d27d      0

[1734 rows x 2 columns]

In [80]:
scores4=pd.concat([scores2,scores3],ignore_index=True)

In [81]:
len(scores4)

1927

In [82]:
def segre(x):
    if x>0:
        return('Good')
    else:
        return("Bad")

In [83]:
scores4['Good_Bad']=scores4.score.apply(lambda x:segre(x))

In [84]:
scores4

                person1  score Good_Bad
0     bb891fa8_b2f18316      0      Bad
1     3166f635_244cda27      0      Bad
2     fc9f1cf6_5bb90d16      0      Bad
3     d2c95676_56a7db59      0      Bad
4     77e4333b_485ca1e6      1     Good
5     52907b87_aa3e7910      1     Good
6     24ca4fa8_f7eb271e      1     Good
7     6b33b3f0_80fae05e      1     Good
8     a562d5f5_714daa7a      0      Bad
9     8bfea6e5_fc9819c1      1     Good
10    2e2c0f72_7ce29cd5      0      Bad
11     ba83348_f625882d      1     Good
12    864387cb_ebe19acc      1     Good
13    9bb080d0_5473c0c0      1     Good
14    d80e3379_bb910b49      1     Good
15    897097bc_948625b8      0      Bad
16    d95ef670_2948deeb      1     Good
17    edfbcfc7_8f6b302b      1     Good
18    7d3ea0b0_fd3600a1      1     Good
19    1adad7eb_80ee595e      0      Bad
20    3e7a6ce5_2ca91616      0      Bad
21    29e3ed08_66de7ee9      1     Good
22    eee5dfae_262cf07a      1     Good
23    8d8bb078_cacdfee6      1     Good
24    21aedee7_9068bb32      1     Good
25    e4f7319d_c82b0c40      0      Bad
26    edd3bd14_3c8c37e6      1     Good
27     8875cac_3871a3fa      0      Bad
28    18ecf508_4ebf64bf      0      Bad
29    7e4940e8_aeb1a832      0      Bad
...                 ...    ...      ...
1897  cab5f7a5_232a7e33      0      Bad
1898  29f2d7e9_7f41056f      0      Bad
1899  44348081_881defa1      0      Bad
1900  49a8ef1b_9478a0da      0      Bad
1901   d64339a_4cfd5078      1     Good
1902  18cd4f6e_822100c7      0      Bad
1903  7a3056e2_f133b6e1      1     Good
1904  3aef501a_80351c26      0      Bad
1905  124119f0_7bd13c7a      0      Bad
1906  bd329c87_ddc0bc01      1     Good
1907  ff4fcf95_ff332153      0      Bad
1908  243a3acc_9ec2034a      0      Bad
1909  1d87cfed_94b71521      0      Bad
1910  3be1998c_341f7318      0      Bad
1911  fe8f223c_5e560689      0      Bad
1912  8506cf40_52804060      0      Bad
1913   ca19cbba_feb5e16      1     Good
1914  8bf42fc8_350a6cf8      0      Bad
1915   c7e135e_44c23c1d      1     Good
1916  a9c7951f_e609e0a0      0      Bad
1917  fcc490fc_e0776c6b      1     Good
1918   71a6ba12_572b668      0      Bad
1919   86aa844_3610fb9b      0      Bad
1920  47e9c22e_5f94a730      0      Bad
1921  6c12ed31_17e2c385      0      Bad
1922  4fbbac4f_511f5390      0      Bad
1923  8067ca9c_976fdb74      0      Bad
1924  560c450d_3c21c3c5      0      Bad
1925  73b8016b_82248c8c      0      Bad
1926  371dc4e1_9a73d27d      0      Bad

[1927 rows x 3 columns]